export const SETUSER = "SETUSER";

export const GET_CUSTOMER_DATA = "GET_CUSTOMER_DATA";
export const UPDATE_CUSTOMER_DATA = "UPDATE_CUSTOMER_DATA";

export const SET_BRANCH = "SET_BRANCH";
export const TOGGLE_BRANCH_FETCHING_STATE = "TOGGLE_BRANCH_FETCHING_STATE";
