export const SETUSER = "SETUSER";

export const GET_CUSTOMER_DATA = "GET_CUSTOMER_DATA";
export const UPDATE_CUSTOMER_DATA = "UPDATE_CUSTOMER_DATA";

export const ADD_PAYEE = "ADD_PAYEE";

export const DELETE_PAYEE = "DELETE_PAYEE";
export const UPDATE_PAYEE = "UPDATE_PAYEE";
